<template>
  <section ref="slide" class="slide relative shrink-0 h-full basis-[100vw] items-center justify-center flex">
    <h2 class="text-4xl font-[Sharetech] uppercase">Welcome to the <span class="text-cyan">cyber cloud</span></h2>
    <BackgroundFigures :figures="squares" />
    <BackgroundFigures :figures="lines" />
  </section>
</template>

<script>
import BackgroundFigures from "@/components/BackgroundFigures.vue";
export default {
  name: "WelcomeSlide",
  components: {BackgroundFigures},
  data() {
    return {
      squares: [
        {
          type: 'fullSquare',
          width: '24px',
          height: '24px',
          backgroundColor: '#00cfcc',
          border: 'none',
          positionX: 'calc(50% - 12px)',
          positionY: '65%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '20px',
          height: '20px',
          backgroundColor: '#00cfcc',
          border: 'none',
          positionX: 'calc(50% - 12px)',
          positionY: '73%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '16px',
          height: '16px',
          backgroundColor: '#00cfcc',
          border: 'none',
          positionX: 'calc(50% - 12px)',
          positionY: '81%',
          animation: true,
        },
        {
          type: 'emptySquare',
          width: '24px',
          height: '24px',
          backgroundColor: 'transparent',
          border: '1px solid #ffffff50',
          positionX: '20px',
          positionY: '90%',
          animation: true,
        },
        {
          type: 'emptySquare',
          width: '20px',
          height: '20px',
          backgroundColor: 'transparent',
          border: '1px solid #ffffff50',
          positionX: '22px',
          positionY: '80%',
          animation: true,
        },
        {
          type: 'emptySquare',
          width: '16px',
          height: '16px',
          backgroundColor: 'transparent',
          border: '1px solid #ffffff50',
          positionX: '24px',
          positionY: '70%',
          animation: true,
        },
        {
          type: 'emptySquare',
          width: '10px',
          height: '10px',
          backgroundColor: 'transparent',
          border: '1px solid #ffffff50',
          positionX: '28px',
          positionY: '10%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '20px',
          height: '20px',
          backgroundColor: '#e898ac',
          border: 'none',
          positionX: '68px',
          positionY: '30%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '20px',
          height: '20px',
          backgroundColor: '#00cfcc',
          border: 'none',
          positionX: '120px',
          positionY: '60%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '12px',
          height: '12px',
          backgroundColor: '#00cfcc',
          border: 'none',
          positionX: '124px',
          positionY: '70%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '12px',
          height: '12px',
          backgroundColor: '#e898ac',
          border: 'none',
          positionX: '22%',
          positionY: '92%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '12px',
          height: '12px',
          backgroundColor: '#ff9973',
          border: 'none',
          positionX: '32%',
          positionY: '86%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '12px',
          height: '12px',
          backgroundColor: '#e898ac',
          border: 'none',
          positionX: '50%',
          positionY: '6%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '9px',
          height: '9px',
          backgroundColor: '#ff9973',
          border: 'none',
          positionX: '60%',
          positionY: '10%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '12px',
          height: '12px',
          backgroundColor: '#ff9973',
          border: 'none',
          positionX: '65%',
          positionY: '40%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '12px',
          height: '12px',
          backgroundColor: '#e898ac',
          border: 'none',
          positionX: '70%',
          positionY: '85%',
          animation: true,
        },
        {
          type: 'emptySquare',
          width: '12px',
          height: '12px',
          backgroundColor: 'transparent',
          border: '1px solid #ffffff60',
          positionX: '71%',
          positionY: '55%',
          animation: true,
        },
        {
          type: 'emptySquare',
          width: '18px',
          height: '18px',
          backgroundColor: 'transparent',
          border: '1px solid #ff997370',
          positionX: '92%',
          positionY: '15%',
          animation: true,
        },
        {
          type: 'emptySquare',
          width: '14px',
          height: '14px',
          backgroundColor: 'transparent',
          border: '1px solid #ffffff60',
          positionX: '93%',
          positionY: '5%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '12px',
          height: '12px',
          backgroundColor: '#e898ac',
          border: 'none',
          positionX: '85%',
          positionY: '25%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '24px',
          height: '24px',
          backgroundColor: '#00cfcc',
          border: 'none',
          positionX: '84%',
          positionY: '80%',
          animation: true,
        },
        {
          type: 'fullSquare',
          width: '16px',
          height: '16px',
          backgroundColor: '#00cfcc',
          border: 'none',
          positionX: '88%',
          positionY: '60%',
          animation: true,
        },
      ],
      lines: [
        {
          type: 'line',
          width: '2px',
          height: '350px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff70)',
          border: 'none',
          positionX: '96%',
          positionY: '10%',
          animation: false,
        },
        {
          type: 'line',
          width: '2px',
          height: '250px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff70)',
          border: 'none',
          positionX: '2%',
          positionY: '20%',
          animation: false,
        },
        {
          type: 'line',
          width: '2px',
          height: '200px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff70)',
          border: 'none',
          positionX: '20%',
          positionY: '-10%',
          animation: false,
        },
        {
          type: 'line',
          width: '2px',
          height: '200px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff70)',
          border: 'none',
          positionX: '13%',
          positionY: '40%',
          animation: false,
        },
        {
          type: 'line',
          width: '2px',
          height: '200px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff60)',
          border: 'none',
          positionX: '35%',
          positionY: '-25%',
          animation: false,
        },
        {
          type: 'line',
          width: '2px',
          height: '200px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff60)',
          border: 'none',
          positionX: '25%',
          positionY: '85%',
          animation: false,
        },
        {
          type: 'line',
          width: '2px',
          height: '200px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff60)',
          border: 'none',
          positionX: '75%',
          positionY: '75%',
          animation: false,
        },
        {
          type: 'line',
          width: '2px',
          height: '250px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff60)',
          border: 'none',
          positionX: '85%',
          positionY: '35%',
          animation: false,
        },
        {
          type: 'line',
          width: '2px',
          height: '200px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff60)',
          border: 'none',
          positionX: '50%',
          positionY: '-30%',
          animation: false,
        },
        {
          type: 'line',
          width: '2px',
          height: '150px',
          backgroundColor: 'linear-gradient(#ffffff05, #ffffff60)',
          border: 'none',
          positionX: '72%',
          positionY: '25%',
          animation: false,
        },
      ]
    }
  },
  mounted() {
    this.$emit('slide', this.$refs.slide);
  }
}
</script>

<style scoped>

</style>